name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_REPO: ${{ vars.DOCKER_USERNAME }}/open-webui
  UPLOAD_LATEST: "true"

jobs:
  build_and_deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Build Docker Container
        run: |
          TMPDIR=$(mktemp -d)
          sudo ./src/scripts/apply.sh

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/main'

      - name: Publish Docker Container
        shell: bash
        run: |
          docker images
          [ "${{ env.UPLOAD_LATEST }}" = false ] && docker rmi ${DOCKER_REPO}:latest
          docker push ${DOCKER_REPO} --all-tags
        if: github.ref == 'refs/heads/main'